# Generated by Django 4.1.7 on 2023-04-08 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_registration_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='institute',
            field=models.CharField(default='PUCIT', max_length=200),
        ),
        migrations.AddField(
            model_name='registration',
            name='roll_no',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
